# Kaggle Competition:  Iceberg or Ship

## Notebook 3
## run resnext50 architecture

In [1]:
!ls -l

total 520
-rw-rw-r-- 1 ubuntu ubuntu 120926 Jan  8 22:22 1_getdata.ipynb
-rw-rw-r-- 1 ubuntu ubuntu 245611 Jan  9 00:26 2_model_resnet34.ipynb
-rw-rw-r-- 1 ubuntu ubuntu  20732 Jan  9 00:41 3_model_resnext50.ipynb
-rw-rw-r-- 1 ubuntu ubuntu 134887 Jan  8 21:26 baseline.ipynb
-rw-rw-r-- 1 ubuntu ubuntu    185 Jan  8 22:18 README.md


In [2]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
from fastai.imports import *

In [4]:
# This file contains all the main external libs we'll use
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *
import pandas as pd
import numpy as np
import shutil
from IPython.display import FileLink, FileLinks

from sklearn.model_selection import train_test_split


In [5]:
#!ls /home/nidhin/data/iceberg
!ls -l /home/ubuntu/data/iceberg

total 1973260
drwxrwxr-x  2 ubuntu ubuntu       4096 Jan  9 00:38 models
-rw-rw-r--  1 ubuntu ubuntu     117951 Oct 23 17:27 sample_submission.csv
-rw-rw-r--  1 ubuntu ubuntu      38566 Jan  7 20:36 sample_submission.csv.7z
drwxrwxr-x  2 ubuntu ubuntu     274432 Jan  8 21:46 test
-rw-rw-r--  1 ubuntu ubuntu 1521771850 Oct 23 17:27 test.json
-rw-rw-r--  1 ubuntu ubuntu  257127394 Jan  7 20:36 test.json.7z
drwxrwxr-x 41 ubuntu ubuntu       4096 Jan  9 00:28 tmp
drwxrwxr-x  4 ubuntu ubuntu       4096 Jan  8 21:45 train
-rw-rw-r--  1 ubuntu ubuntu  196313674 Oct 23 17:23 train.json
-rw-rw-r--  1 ubuntu ubuntu   44932785 Jan  7 20:36 train.json.7z
drwxrwxr-x  4 ubuntu ubuntu       4096 Jan  8 21:45 valid


In [6]:
#PATH = "/home/nidhin/data/iceberg/"
PATH = "/home/ubuntu/data/iceberg/"

In [7]:
!ls -l {PATH}

total 1973260
drwxrwxr-x  2 ubuntu ubuntu       4096 Jan  9 00:38 models
-rw-rw-r--  1 ubuntu ubuntu     117951 Oct 23 17:27 sample_submission.csv
-rw-rw-r--  1 ubuntu ubuntu      38566 Jan  7 20:36 sample_submission.csv.7z
drwxrwxr-x  2 ubuntu ubuntu     274432 Jan  8 21:46 test
-rw-rw-r--  1 ubuntu ubuntu 1521771850 Oct 23 17:27 test.json
-rw-rw-r--  1 ubuntu ubuntu  257127394 Jan  7 20:36 test.json.7z
drwxrwxr-x 41 ubuntu ubuntu       4096 Jan  9 00:28 tmp
drwxrwxr-x  4 ubuntu ubuntu       4096 Jan  8 21:45 train
-rw-rw-r--  1 ubuntu ubuntu  196313674 Oct 23 17:23 train.json
-rw-rw-r--  1 ubuntu ubuntu   44932785 Jan  7 20:36 train.json.7z
drwxrwxr-x  4 ubuntu ubuntu       4096 Jan  8 21:45 valid


In [8]:
sz=299
arch=resnext50
bs=20

In [9]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs, num_workers=4)
learn = ConvLearner.pretrained(arch, data, precompute=True, ps=0.5)

In [11]:
learn.fit(1e-2, 8)
learn.precompute=False

HBox(children=(IntProgress(value=0, description='Epoch', max=8), HTML(value='')))

[ 0.       0.56924  0.40189  0.80588]                      
[ 1.       0.53197  0.41626  0.81176]                      
[ 2.       0.47842  0.4166   0.80882]                      
[ 3.       0.5327   0.50349  0.76471]                      
[ 4.       0.5058   0.43262  0.82647]                      
[ 5.       0.54853  0.41028  0.83823]                      
[ 6.       0.57066  0.49921  0.78824]                      
[ 7.       0.54218  0.42668  0.78824]                      



In [12]:
learn.fit(1e-2, 4, cycle_len=2)

HBox(children=(IntProgress(value=0, description='Epoch', max=8), HTML(value='')))

[ 0.       0.46353  0.38343  0.84706]                      
[ 1.       0.43165  0.38153  0.82941]                      
[ 2.       0.40987  0.38472  0.83235]                      
[ 3.       0.38102  0.37537  0.82941]                      
[ 4.       0.40039  0.39405  0.82059]                      
[ 5.       0.42393  0.39045  0.83235]                      
[ 6.       0.4329   0.36448  0.82353]                      
[ 7.       0.38624  0.36672  0.83529]                      



In [13]:
learn.unfreeze()
lr=np.array([1e-4,1e-3,1e-2])

In [15]:
learn.fit(lr, 3, cycle_len=3)

HBox(children=(IntProgress(value=0, description='Epoch', max=9), HTML(value='')))

[ 0.       0.33704  0.86248  0.67353]                      
[ 1.       0.28617  0.36131  0.80294]                      
[ 2.       0.23445  0.37927  0.81471]                      
[ 3.       0.25762  0.72652  0.72353]                      
[ 4.       0.21814  0.34146  0.84706]                      
[ 5.       0.18997  0.34428  0.85   ]                      
[ 6.       0.22553  0.32775  0.86177]                      
[ 7.       0.22584  0.36472  0.85588]                      
[ 8.       0.15291  0.37712  0.85882]                      



In [16]:
learn.save('224_all_50')

In [17]:
learn.load('224_all_50')

In [18]:
log_preds,y = learn.TTA()
accuracy(log_preds,y)

AttributeError: 'bool' object has no attribute 'mean'