# Kaggle Competition:  Iceberg or Ship

## Notebook 3
## run resnext50 architecture

In [1]:
!ls -l

total 1864
-rw-rw-r-- 1 nidhin nidhin 623462 Jan 13 22:48 1_getdata.ipynb
-rw-rw-r-- 1 nidhin nidhin 245619 Jan 13 21:50 2_model_resnet34.ipynb
-rw-rw-r-- 1 nidhin nidhin  14278 Jan 14 01:06 3_model_resnext50-Copy1.ipynb
-rw-rw-r-- 1 nidhin nidhin  30340 Jan 14 17:25 3_model_resnext50.ipynb
-rw-rw-r-- 1 nidhin nidhin  64965 Jan 14 00:26 4_resnext_resize.ipynb
-rw-rw-r-- 1 nidhin nidhin 137540 Jan 14 01:27 baseline.ipynb
-rw-rw-r-- 1 nidhin nidhin    536 Jan 13 19:15 helper.py
-rw-rw-r-- 1 nidhin nidhin 767392 Jan 14 16:25 other_groverpr.ipynb
drwxrwxr-x 2 nidhin nidhin   4096 Jan 13 19:15 __pycache__
-rw-rw-r-- 1 nidhin nidhin    185 Jan 13 17:48 README.md


In [2]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
from fastai.imports import *

In [4]:
# This file contains all the main external libs we'll use
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *
import pandas as pd
import numpy as np
import shutil
from IPython.display import FileLink, FileLinks

from sklearn.model_selection import train_test_split
import helper

In [5]:
#PATH = "/home/nidhin/data/iceberg/"
PATH = os.path.expanduser("~/data/iceberg/")

In [6]:
!ls -l {PATH}

total 1975500
drwxrwxr-x  6 nidhin nidhin       4096 Jan 14 01:19 composites
drwxrwxr-x  2 nidhin nidhin       4096 Jan 13 19:06 models
-rw-rw-r--  1 nidhin nidhin     117951 Oct 23 17:27 sample_submission.csv
-rw-rw-r--  1 nidhin nidhin      38566 Jan  7 20:28 sample_submission.csv.7z
drwxrwxr-x  4 nidhin nidhin       4096 Jan 14 17:22 sub
drwxrwxr-x  2 nidhin nidhin     286720 Jan 13 22:48 test
-rw-rw-r--  1 nidhin nidhin 1521771850 Oct 23 17:27 test.json
-rw-rw-r--  1 nidhin nidhin  257127394 Jan  7 20:28 test.json.7z
drwxrwxr-x 15 nidhin nidhin       4096 Jan 13 21:50 tmp
drwxrwxr-x  4 nidhin nidhin       4096 Jan 13 22:48 train
-rw-rw-r--  1 nidhin nidhin  196313674 Oct 23 17:23 train.json
-rw-rw-r--  1 nidhin nidhin   44932785 Jan  7 20:28 train.json.7z
-rw-rw-r--  1 nidhin nidhin    2275916 Jan  8 01:44 train_modified.zip
drwxrwxr-x  4 nidhin nidhin       4096 Jan 13 22:48 valid


In [7]:
sz=299
arch=resnext50
bs=20

In [8]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs,test_name='test',)
learn = ConvLearner.pretrained(arch, data, precompute=True, ps=0.5)

In [9]:
learn.fit(1e-2, 8)
learn.precompute=False

HBox(children=(IntProgress(value=0, description='Epoch', max=8), HTML(value='')))

[ 0.       0.69323  0.71376  0.71176]                      
[ 1.       0.62528  0.58398  0.70588]                       
[ 2.       0.57636  0.45172  0.80294]                       
[ 3.       0.55199  0.4703   0.79706]                       
[ 4.       0.48557  0.4464   0.82941]                       
[ 5.       0.47288  0.46801  0.79412]                       
[ 6.       0.45848  0.47164  0.80882]                       
[ 7.       0.51028  0.44751  0.81471]                       



In [10]:
learn.fit(1e-2, 4, cycle_len=2)

HBox(children=(IntProgress(value=0, description='Epoch', max=8), HTML(value='')))

[ 0.       0.70789  0.48105  0.75294]                      
[ 1.       0.55353  0.49911  0.75294]                      
[ 2.       0.52519  0.44617  0.77647]                      
[ 3.       0.46936  0.47276  0.77647]                      
[ 4.       0.45942  0.39246  0.82059]                      
[ 5.       0.44453  0.48581  0.77059]                      
[ 6.       0.43383  0.43481  0.8    ]                      
[ 7.       0.46675  0.46652  0.79118]                      



In [11]:
learn.unfreeze()
lr=np.array([1e-4,1e-3,1e-2])

In [12]:
learn.fit(lr, 3, cycle_len=3,)

HBox(children=(IntProgress(value=0, description='Epoch', max=9), HTML(value='')))

[ 0.       0.6032   0.4318   0.78235]                      
[ 1.       0.43402  0.42972  0.80882]                      
[ 2.       0.3596   0.5016   0.78824]                      
[ 3.       0.41441  0.58758  0.70882]                      
[ 4.       0.47549  0.66059  0.73529]                      
[ 5.       0.46787  0.68278  0.7    ]                      
[ 6.       0.48694  0.73478  0.70588]                      
[ 7.       0.42102  0.84079  0.70588]                      
[ 8.       0.37834  0.96813  0.66177]                      



In [13]:
learn.save('224_all_50')

In [14]:
learn.load('224_all_50')

In [15]:
log_preds,y = learn.TTA()
preds = np.mean(np.exp(log_preds),axis=0)
(metrics.log_loss(y,preds), accuracy(preds,y))

(0.33778778430372924, 0.84423676012461057)

In [19]:
helper.make_submission(learn=learn
               ,data=data
               ,output_file_name = f'{PATH}/sub/resnext50_sz299_bs20_colorscale_ordered.csv'
               )

In [21]:
submmission_df = pd.read_csv(f'{PATH}/sub/resnext50_sz299_bs20_colorscale_ordered.csv')

In [23]:
len(submmission_df)

8424